print("Milan")
# print("Hello World")
print("True or False is ", True or False )
print("True or True  is ", True or True  )
print("False or True is " ,False or True )
print("False or False is ", False or False )